### PR TITLE
Sanitize fdtracker unserialization

### PR DESCRIPTION
**Pull request by ArneBab**
This might fix the startup loop bug likely caused as a side effect of fixing the lose-all-downloads-on-restart bug.

Symptoms of the bug: Massive memory requirement on startup, continuously restart.

### CODE REVIEW

**Comment by ArneBab** [comment]
Tested by BadLuckBob now, but did not resolve the problem :-/

**Comment by gits7r** [comment]
I have run into the same bug, massive memory requirement on startup, continuously restarts but I did not have any ongoing downloads or anything in the download queue. In fact, I did not download anything at all from that particular node never (not just before the last restart before the continuous restarts. So, I doubt there was some queue that needed deserialization when I tried to start fred and did not work. We have to check and make sure.

Is `fdtracker` also used by other kind of (automated) downloads such as datastore refresh and not just for manual downloads requested by users by presenting the SSK (or keys)?

**Comment by ArneBab** [comment]
This is in the PooledFileRandomAccessBuffer, so yes, this is used for example when inserting splitfiles.

**Comment by ArneBab** [comment]
Closed in favor of https://github.com/freenet/fred/pull/686 which actually worked.

**Pull request closed without merging**
