### PR TITLE
Update SSL code

### PR DESCRIPTION
**Pull request by bertm**
This updates the SSL code so that it works on Java 8+ (as well as on Java 7), and uses more up-to-date crypto algorithms and protocols. In addition, this includes a few cleanups and error message improvements.

### CODE REVIEW

**Comment by bertm** [comment]
(not that I really care about this functionality, but is was easier to fix than to remove)

**Comment by nextgens** [comment]
Hmfff. Don't create 2048 bit RSA keys ; Try to be consistent with a security-level:
https://www.keylength.com/en/3/

Make a p256 key if need be... and switch to the ECDSA version of the cipher

**Comment by bertm** [comment]
Thanks for the suggestion, fixed.

**Comment by nextgens** [comment]
I haven't tested it but lgtm

**Pull request merged**
