### PR TITLE
Prioritise memory jobs

### PR DESCRIPTION
**Pull request by toad**
Priorities for MemoryLimitedJob's, i.e. FEC decode/encode jobs. Please check the call stack to ensure that there are no locking issues, but there shouldn't be any.

This should ensure that fproxy is reasonably responsive even when there are big files completing, and mitigate the damage caused by BC < 1.52 with encrypted disk enabled.

### CODE REVIEW

**Comment by toad** [comment]
I have re-reviewed this and IMHO there are no hidden concurrency issues. This should be safe. It seems to work well in my local testing too.

**Comment by toad** [comment]
It is however less important to get this out quickly provided we can get #382 out soon.

**Comment by toad** [comment]
A full solution to "stalls for hours at 100% CPU and misses the update" does require both patches I guess...

**Comment by Thynix** [comment]
Are people happy with this?

**Pull request merged**
