### PR TITLE
add required module opens for Java 17 to wrapper.conf

### PR DESCRIPTION
**Pull request by ArneBab**

### CODE REVIEW

**Comment by Darwin1546** [comment]
Currently Freenet doesn't work with 17 adoptium java.
If this is the fix, what do we waiting for?

**Comment by ArneBab** [comment]
Darwin1546 ***@***.***> writes:

> Currently Freenet doesn't work with 17 adoptium java.
> If this is the fix, what do we waiting for?

Yes, this is the fix. I need to prepare the release. Wanted to get it
prepared last weekend, I hope I’ll manage this one.

Best wishes,
Arne
-- 
Unpolitisch sein
heißt politisch sein,
ohne es zu merken.
draketo.de

**Comment by Thynix** [comment]
I can't claim to have much domain knowledge, but this looks good to me.

**Comment by ArneBab** [comment]
@Thynix  Thank you for reviewing!

**Pull request merged**
