### PR TITLE
Removed several usages of the deprecated Closer

### PR DESCRIPTION
**Pull request by JanGerritsen**
Closer is deprecated and can often be replaced by try with closeable statements.
In this PR several such places have been refactored. 
A few cases also fix potential leaks where resources are not closed probably in all cases.

### CODE REVIEW

**Comment by desyncr** [comment]
@JanGerritsen Thanks for the work! It could take a while to review it and be sure we don't break anything :)

I haven't been able to carefully review the code so far, but there's a mix of tabs and spaces causing some indentation issues.

**Comment by JanGerritsen** [comment]
@desyncr: I am Sorry, but the files use mixed tabs and spaces and I opted to use tabs, because that's what seems to be used mostly.

Has there been a try to define a standard code style for fred?

**Comment by desyncr** [comment]
I think the default standard is tabs. [Here](https://github.com/freenet/fred/pull/706/files#diff-064ded8a866a9193072429b727bed45bR1230)'s a mix of tabs and spaces.

**Comment by JanGerritsen** [comment]
Yes I know. I tried to preserve Identation as much as I could, to make the diff not bigger than it needs to be, but well, the whole file already uses a mix.

I would suggest that there should be a defined format, and then to create one merge request, were someone just does the reformat of the project.
Afterwards it would be much easier to create pull requests, which show what has actually changed, not just reformatted.

But this would need to be a coordinated effort and one needs to a agree on a standard formater...

**Comment by desyncr** [comment]
Sure, one or multiple PRs just fixing standard issues.

**Comment by ArneBab** [comment]
Looks good and the tests pass. Merged.

**Pull request merged**
