### PR TITLE
Update license to GPLv3 only

### PR DESCRIPTION
**Pull request by freesoftwarerocks**
Effective binary is GPLv3 only

### CODE REVIEW

**Comment by freesoftwarerocks** [comment]
update license as GPL-3-only

**Comment by ArneBab** [comment]
This needs a lot more explanation than just "Effective binary is …".

I prefer GPLv3 or later to GPLv2 or later, but switching to GPLv3 only reduces long-term compatibility and copyleft safety compared to GPLv2 or later. Also you don’t just change the license of an existing project.

**Comment by freesoftwarerocks** [comment]
> This needs a lot more explanation than just "Effective binary is …".
> 
> I prefer GPLv3 or later to GPLv2 or later, but switching to GPLv3 only reduces long-term compatibility and copyleft safety compared to GPLv2 or later. Also you don’t just change the license of an existing project.

freenet includes code that is apache v2 licensed and it is only compatible with GPLv3 only. Since freenet is GPLv2 or later, mixing codes together produces a binary that is GPLv3 only

**Comment by freesoftwarerocks** [comment]
> This needs a lot more explanation than just "Effective binary is …".
> 
> I prefer GPLv3 or later to GPLv2 or later, but switching to GPLv3 only reduces long-term compatibility and copyleft safety compared to GPLv2 or later. Also you don’t just change the license of an existing project.

https://gitlab.com/inkscape/inkscape/-/blob/master/COPYING

Inkscape is under GPLv2 or later, but includes an LGPLv3 or later library so the binary as a whole is under GPLv3 or later

**Comment by freesoftwarerocks** [comment]
> This needs a lot more explanation than just "Effective binary is …".
> 
> I prefer GPLv3 or later to GPLv2 or later, but switching to GPLv3 only reduces long-term compatibility and copyleft safety compared to GPLv2 or later. Also you don’t just change the license of an existing project.

[Apache License, Version 2.0](https://directory.fsf.org/wiki/License:Apache2.0) ([#apache2](https://www.gnu.org/licenses/license-list.en.html#apache2))
This is a free software license, compatible with version 3 of the GNU GPL.

Please note that this license is not compatible with GPL version 2, because it has some requirements that are not in that GPL version. These include certain patent termination and indemnification provisions. The patent termination provision is a good thing, which is why we recommend the Apache 2.0 license for substantial programs over other lax permissive licenses.

**Comment by ArneBab** [comment]
That’s what’s already written in the README. Our code, however — which is what you get from this repository — is released under GPLv2 *or later*. This allows releasing binaries as GPLv3.

I would merge a PR that only changes the license information of a released binary or providing multiple LICENSE files, but as project we should not merge a change to the license information of the GPLv2 or later code.

**Comment by ArneBab** [comment]
@freesoftwarerocks I now closed the pull request after getting no reply for 9 days.

If you want to implement a version that limits the changes to what’s released as binaries or to the info in the web interface, then feel free to re-open the pull-request.

**Pull request closed without merging**
