### PR TITLE
Ogg - Theora fixes

### PR DESCRIPTION
**Pull request by Olezha**
I hope these changes will allow to play videos.

### CODE REVIEW

**Comment by Thynix** [comment]
A parsing error doesn't seem like it should be an `IOException` - is the filter infrastructure flexible enough to make it easy to use something more semantically meaningful (maybe a `FormatException`?) or is this the only practical path?

**Comment by Thynix** [comment]
Other than that these changes look good to me; thanks for posting this!

**Comment by ArneBab** [comment]
I’ll still be overloaded for a bit more than two weeks, afterwards I hope I’ll be able to quickly get this into a test release. Thank you!

**Comment by ArneBab** [comment]
Short heads up: I did a quick local test and could watch the test file right in Freenet: CHK@SLY4fFXoHwfLMTApgLDwZhc1S63vN4Thgm0E5RO7i1A,-oR~EQ2NU4X1~Gfj1KeU2sRomD8e6VJsozHs~vrnMIs,AAMC--8/sofie2014-cropped.ogg

Thank you very much!

**Pull request merged**
