### PR TITLE
Manifest putter fix mime type guessing

### PR DESCRIPTION
**Pull request by ArneBab**
Sharewiki and Freereader work again.

→ old: http://127.0.0.1:8888/KeyUtils/Site/?mftype=TARmanifest&key=SSK@pFAHc9wpvLztZ4hYor2qYH54lYTYF6j6Pbg6Mqy5-bM,SPN7S~kYzaggMCCavc46mBxsrI5gTrtcc5JP4aXCTtg,AQACAAE/Test-1&hexwidth=32&deep=checked
→ new: http://127.0.0.1:8888/KeyUtils/Site/?mftype=TARmanifest&key=SSK@pFAHc9wpvLztZ4hYor2qYH54lYTYF6j6Pbg6Mqy5-bM,SPN7S~kYzaggMCCavc46mBxsrI5gTrtcc5JP4aXCTtg,AQACAAE/Test-3&hexwidth=32&deep=checked

This still needs someone who managed to setup junit4 to check whether all tests run.

Fixes bug 0006385 and bug 0006446:
- https://bugs.freenetproject.org/view.php?id=6385
- https://bugs.freenetproject.org/view.php?id=6446

### CODE REVIEW

**Comment by Thynix** [comment]
Could you squash "Fix docstring for getMimeType" into "Add getMimeType() to ManifestElement" please?

**Comment by Thynix** [comment]
The tests pass! I'll either merge this after the changes to the commits or I can do it if you prefer.

**Comment by ArneBab** [comment]
I adjusted the commits. Merge-ready?

**Comment by Thynix** [comment]
Yup.

**Comment by Thynix** [comment]
The content and commit messages are fine, but the usage of getMimeType() is now before its addition.

**Comment by ArneBab** [comment]
dang… sorry. 

Give me a few minutes

**Comment by ArneBab** [comment]
Ah, no, in terms of the DAG, the order should be right. Just the date for the commits is wrong (due to folding the later one into adding getMimeType() but using the later date).

**Comment by Thynix** [comment]
Indeed you are right; I didn't realize GitHub did that. Thanks for writing this!

**Comment by ArneBab** [comment]
I also did not know that Github would display it wrong - when I saw your comment here I looked at the commits in the github UI and thought I had made a mistake. But it was right in Mercurial, and since the bridge between hg and git is transparent (at least from the hg side) I was almost sure that git should be correct, too.

**Pull request merged**
