### PR TITLE
bug6562: mark temporary files as hidden

### PR DESCRIPTION
**Pull request by nextgens**
This should do the trick; I haven't tested it on windows

### CODE REVIEW

**Comment by bertm** [comment]
Are you sure changing these filenames does not break existing persistent downloads?

Apart from possible persistence issues, the code looks sane :)

**Comment by nextgens** [comment]
I haven't tested it, but considering that it's calls to File.createTempFile() that I have changed, I think it will be fine.

**Comment by Thynix** [comment]
Are temporary files moved to the destination filename? I haven't tested it
(and won't have time to until next week) but that seems to mean on Windows
that those files will have to be set to not hidden if desired.

**Comment by nextgens** [comment]
I think that we copy from an encrypted bucket to a new file in ClientGetter... but yes, it deserves to be tested :)

**Comment by bertm** [comment]
Will test in a few days.

Op 20 aug. 2016 18:37 schreef "Florent Daigniere" <notifications@github.com

**Comment by bertm** [comment]
Tested working on Linux when switching from `next` to your branch with pending downloads.

**Comment by ArneBab** [comment]
@bertm does that mean you consider this ready to be merged?

**Comment by ArneBab** [comment]
did anyone test this under Windows?

**Comment by ArneBab** [comment]
This makes Freenet fail under Windows 8.1: 

> Under Windows you can set the hidden flag on any file (e.g. text.txt). And if it is set, but the writeable flag is not set then you can edit the file but never save it until the hidden flag is cleared. And the error message is not very clear in what was wrong. 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=194216

I’ll revert this change.

**Comment by nextgens** [comment]
That's fine; I've explicitly said it hadn't been tested... you've merged it without testing it :|

**Comment by nextgens** [comment]
That's fine.

**Pull request merged**
