### PR TITLE
Show peer locations, not distance in peer location histogram

### PR DESCRIPTION
**Pull request by bertm**
As discussed on devl.

### CODE REVIEW

**Comment by Thynix** [comment]
This looks like it works as intended in my testing. Thanks!

**Comment by xor-freenet** [comment]
The commit of this pull request was not gpg-signed.
Bert, can you please use "--gpg-sign" with "git commit" in the future?

**Comment by bertm** [comment]
Correct, none of my commits have ever been signed as far as I can remember. I technically could sign future commits, but I'm not convinced of the merits of doing so.

How would signing help? I hope my pull requests are judged on their contents, not on the presence of my signature.

**Comment by xor-freenet** [comment]
Standard site to explain this is: https://mikegerwitz.com/papers/git-horror-story
Hence we had established the consensus that everyone should sign their commits. Admittedly, it does seem to be lacking in CONTRIBUTING.md, sorry.

**Comment by xor-freenet** [comment]
(TL;DR: People who merge your code can modify the commits as they please and write your name on them, there is no mechanism of marking commits as untampered with EXCEPT for GPG-signing them. In fact, git even provides standard features for arbitrarily modifying commits. git commit --amend, etc.)

**Comment by xor-freenet** [comment]
Bug filed: "CONTRIBUTING.md should ask developers to gpg-sign their commits" https://bugs.freenetproject.org/view.php?id=6731

**Pull request merged**
