### PR TITLE
Some experimental code trying to get rid of legacy

### PR DESCRIPTION
**Pull request by nextgens**
Don't consider running it without backups.

NOT READY FOR MERGING

### CODE REVIEW

**Comment by Thynix** [comment]
In addition to the bug fixes, does this need anything to go mandatory before it can be deployed?

**Comment by nextgens** [comment]
nope; it's all about removing what should be dead-code

**Comment by Thynix** [comment]
We talked in IRC about this. To make sure I understand - is opennet/announcement broken for all nodes or only between nodes with these changes and nodes 3 years old or older?

**Comment by nextgens** [comment]
I'll split this up in several safer PRs instead

**Pull request closed without merging**
