### PR TITLE
CSS: more 1471 fixes

### PR DESCRIPTION
**Pull request by toad**
A few minor fixes to the CSS changes. Removes some keywords that shouldn't be allowed, adds some that should. Can wait.

### CODE REVIEW

**Comment by Thynix** [comment]
What does it add? I only see removing "space-between", "space-around", and "space-evenly" from "align-items". What does the "justify-items" change fix?

**Comment by Thynix** [comment]
It removes left, center, and right - the strings are references to other array indexes.

**Comment by Thynix** [comment]
Er, I'm wrong. I still don't understand what exactly it changes.

**Comment by Thynix** [comment]
I think I got it now?

For <justify-items> it used to accept "left legacy", "center legacy", "right legacy", "legacy left", "legacy center", or "legacy right" before or after "center", "start", "end", "self-start", "self-end", "flex-start", "flex-end", "left", or "right". Instead of the former set it now only accepts "true" or "safe".

I still don't understand why though.

**Comment by Thynix** [comment]
Why change `justify-items`? [The spec](http://www.w3.org/TR/css3-align/#justify-items-property) indicates the previous values were accepted, does it not?

**Comment by toad** [comment]
align-items doesn't accept the 3 keywords I deleted.

**Comment by Thynix** [comment]
Okay, but what about `justify-items`?

**Comment by toad** [comment]
justify-items accepts any one of the auxiliary verifiers 125, 129 and 130.

125 is auto, stretch or baseline-position.
129 is the last bit: legacy && [left|right|center]: legacy left, right legacy, center etc.
- This is made of 128 (legacy) and 4 (left|right|center)
That leaves 130 which should be "item-position && overflow-position?" e.g. "start true" etc.

The new code has 130 = combinations of 122 and 126. 122 is overflow-position, 126 is item-position.
The old code had 130 = combinations of 129 and 126. This is incorrect - we don't want the legacy keyword here, and there are more item-positions than left, right, center.

**Comment by Thynix** [comment]
Alright, so. We finally got me to understand this:

`<justify-items>` used to accept `<item-position>` along with `legacy && [ left | right | center ]`, which is incorrect. It now accepts `<item-position>` along with `<overflow-position>`, to match http://www.w3.org/TR/css3-align/#justify-items-property

**Pull request merged**
