### PR TITLE
Resume ClientPutDir.manifestElements on startup, fixes NPE

### PR DESCRIPTION
**Pull request by toad**

### CODE REVIEW

**Comment by bertm** [comment]
Why should `ClientPutDir` know about `ContainerInserter` at all? `DefaultManifestPutter` in instance variable `putter` is supposed to handle these implementation details. Why not resume the putter instead?

**Comment by toad** [comment]
True, the method needs moving somewhere more appropriate.

**Comment by ArneBab** [comment]
is there a solution where to put the method?

**Comment by Thynix** [comment]
Any word on this?

**Comment by Thynix** [comment]
Poke poke.

**Comment by toad** [comment]
I don't see why we can't just merge this? It's ugly but it's not really violating any meaningful layering?

**Pull request merged**
