### PR TITLE
Recreate message, as required

### PR DESCRIPTION
**Pull request by toad**
Should be trivial log fix for swapping. But needs testing on actual darknet nodes, or at least on a hybrid node (such as mine).

### CODE REVIEW

**Comment by Thynix** [comment]
I don't understand why this is doing what it does.

**Comment by toad** [comment]
DMT/inter-node messages can have sub-messages, which can take up space and propagate information that ought not to be propagated (maybe even used for tracing across the network by a passive attacker). Recreating the message explicitly is therefore preferable to forwarding the original message. There is an existing warning message in the MessageCore code to check for this.

**Comment by bertm** [comment]
This looks like duplication of logic. Why not use `Message.cloneAndDropSubMessages()`?

**Comment by Thynix** [comment]
@toad Ping.

**Comment by toad** [comment]
Because the ID changes?

**Comment by Thynix** [comment]
The incomingID? I don't follow. Why does it change?

**Comment by toad** [comment]
The ID on the message changes, because we change it from incoming to outgoing, or vice versa?

**Comment by bertm** [comment]
Ah, of course.

In retrospect, this is more reasonable than I originally thought, as it is consistent with how swap replies are generated in `run()`, however relaying the swap reply (for a forwarded swap request) instead of generating it.

**Pull request merged**
