### PR TITLE
fproxy-page: sanitize the content of the key input field

### PR DESCRIPTION
**Pull request by ArneBab**
With this change, the fetch key field can be used with an anchor as well as with links which use the default host and port. That allows telling users to just put a Freenet link into that fetch field (which also avoids attacks from putting a key into the url field of the browser).

### CODE REVIEW

**Comment by bertm** [comment]
9bf078b should not be part of this pull request.

**Comment by ArneBab** [comment]
@bertm including that wasn’t intentional.

**Comment by ArneBab** [comment]
Can you estimate the effort for switching to a POST request? I likely won’t have much time to work on this the next weeks.

**Comment by ArneBab** [comment]
I think you’re right ☹

Bombe would say that I have to differentiate between easy solutions and too easy solutions which break things.

**Comment by nextgens** [comment]
I've implemented it differently in #551 please review :)

**Pull request closed without merging**
