### PR TITLE
Truecrypt is now Veracrypt

### PR DESCRIPTION
**Pull request by nextgens**

### CODE REVIEW

**Comment by toad** [comment]
I thought the decision was not to explicitly recommend Truecrypt any more? I believe the wizard links to the Wikipedia list of disk encryption software - so if we're recommending TC in the security levels page, this is a bug?

**Comment by nextgens** [comment]
Feel free to send a better PR :)

**Comment by ArneBab** [comment]
I think this bugfix is good. No change in behaviour, just a fix for a no longer valid string.

**Comment by nextgens** [comment]
#444 is doing the same

**Pull request closed without merging**
