### PR TITLE
Fix legacy UOM (updated based on Steve's merge and one key fix)

### PR DESCRIPTION
**Pull request by toad**
The final commit here is an important fix. The rest is from steve's java7-legacy-uom branch, which includes my fixes from the previous pull request #494

### CODE REVIEW

**Comment by toad** [comment]
This seems to work now, it's just rather painful to test. You have to set up both the nodes' update keys and NodeUpdateManager's current and transition keys and Version.java ...

**Comment by Thynix** [comment]
Hint: [build_autoupgrade](https://github.com/freenet/scripts/blob/master/build_autoupgrade) does this.

**Comment by Thynix** [comment]
As expected, because there is no blob-level change, when running with [my java7-legacy-uom](https://github.com/thynix/fred-staging/tree/java7-legacy-uom), which offers the correct URI:

> Failed to fetch main jar 1471 from blob from 127.0.0.1:49032 : Upstream

**Comment by Thynix** [comment]
[test-autoupgrade](https://github.com/freenet/scripts/blob/master/test-autoupgrade) now exists, which requires:

* a running node with FCP on port 9481 (to generate keys)
* [pyFreenet](https://github.com/freenet/pyFreenet/) installed
* Fred (this repository) in ../fred
* [java_installer](https://github.com/freenet/java_installer) in ../java_installer

With that it will:

* build 1470, 1471, and 1472, with 1470 based on build01470, and the others self-mandatory and based on [java7-legacy-uom](https://github.com/thynix/fred-staging/tree/java7-legacy-uom)
* start an UpgradeTarget node with 1470
* start an Upstream node with 1472 
* connect the nodes over darknet
* insert 1471 to the legacy insert key and new insert key, and 1472 to the new insert key

As of this writing - on Upstream commit 87d766b6bfae54bec49ad3688a87a57a4c868782 - the behavior of the UpgradeTarget is to upgrade over UOM to 1471, then repeatedly fail to upgrade to 1472:

    Fetching main jar from 192.168.1.83:5478 : Upstream
    Receiving main jar 1472 from 192.168.1.83:5478 : Upstream
    Failed to transfer main jar 1472 from freenet.node.DarknetPeerNode@93ca50d@192.168.1.83:5478@a200307b06005410a25bad5f4e25ccf724b4ed5d4069c810c0ce3e9de1c8221a@70f951bb

with the reason for the failure being disconnection:

    Jan 31, 2016 23:37:00:203 (freenet.io.xfer.PartiallyReceivedBulk, Main jar (1472) receive for 7359143716976983843 from 192.168.1.83:5478 : Upstream(51), NORMAL): Aborting freenet.io.xfer.PartiallyReceivedBulk@331f00af: 7 : Sender disconnected first missing is 15
    java.lang.Exception: debug
    	at freenet.io.xfer.PartiallyReceivedBulk.abort(PartiallyReceivedBulk.java:145)
    	at freenet.io.xfer.BulkReceiver.receive(BulkReceiver.java:79)
    	at freenet.node.updater.UpdateOverMandatoryManager$12.run(UpdateOverMandatoryManager.java:1415)
    	at freenet.support.PooledExecutor$MyThread.innerRun(PooledExecutor.java:248)
    	at freenet.support.PooledExecutor$MyThread.realRun(PooledExecutor.java:188)
    	at freenet.support.io.NativeThread.run(NativeThread.java:157)
    Jan 31, 2016 23:37:00:203 (freenet.node.DarknetPeerNode, Main jar (1472) receive for 7359143716976983843 from 192.168.1.83:5478 : Upstream(51), MINOR): Sending async: FNPBulkReceiveAborted {uid=7359143716976983843} : null on freenet.node.DarknetPeerNode@93ca50d@192.168.1.83:5478@a200307b06005410a25bad5f4e25ccf724b4ed5d4069c810c0ce3e9de1c8221a@70f951bb for 57951 priority 2
    Jan 31, 2016 23:37:00:203 (freenet.node.DarknetPeerNode, Scheduled job: freenet.node.NodeDispatcher$3@6b955910(57), MINOR): Peer node status now 5 was 3
    Jan 31, 2016 23:37:00:203 (freenet.node.updater.UpdateOverMandatoryManager$12, Main jar (1472) receive for 7359143716976983843 from 192.168.1.83:5478 : Upstream(51), ERROR): Failed to transfer main jar 1472 from freenet.node.DarknetPeerNode@93ca50d@192.168.1.83:5478@a200307b06005410a25bad5f4e25ccf724b4ed5d4069c810c0ce3e9de1c8221a@70f951bb

Merging #398 for Upstream does not change this behavior.

**Comment by Thynix** [comment]
My time for the project has been scarce lately, but I hope to:

* Insert updates serially instead of in parallel in the hope that avoids encountering an "internal error" on the inserts.
* Change the wrapper configuration to allow remote debugging. (Running with the wrapper is required for UOM to be active; configuring this seems easier than changing that.)

**Comment by Thynix** [comment]
I've done the first thing but not the second. ArneBab suggests investigating whether the 1471 and 1472 builds made by the testing script sharing a mandatory date could be causing problems. I plan to investigate that too. (Or someone else is welcome to beat me to it. :))

**Comment by Thynix** [comment]
Given that it seems to be related to disconnections Arne was wondering if `timeLastReceivedDataPacket` not being updated caused problems; I tried with always updating `timeLastReceivedPacket`, and the behavior is the same: 1470 prompts to upgrade to 1471, fetches, and applies the upgrade, but once upgraded to 1471 prompts to fetch 1472 and fails to transfer it.

```
diff --git a/src/freenet/node/PeerNode.java b/src/freenet/node/PeerNode.java
index bd60b28..fffba1d 100644
--- a/src/freenet/node/PeerNode.java
+++ b/src/freenet/node/PeerNode.java
@@ -1872,7 +1872,13 @@ public abstract class PeerNode implements USKRetrieverCallback, BasePeerNode, Pe
 	*/
 	@Override
 	public void receivedPacket(boolean dontLog, boolean dataPacket) {
+    long now = System.currentTimeMillis();
 		synchronized(this) {
+      timeLastReceivedPacket = now;
+      if (dataPacket) {
+        timeLastReceivedDataPacket = now;
+      }
+
 			if((!isConnected()) && (!dontLog)) {
 				// Don't log if we are disconnecting, because receiving packets during disconnecting is normal.
 				// That includes receiving packets after we have technically disconnected already.
@@ -1887,12 +1893,6 @@ public abstract class PeerNode implements USKRetrieverCallback, BasePeerNode, Pe
 				if(logMINOR) Logger.minor(this, "Received packet on "+this);
 			}
 		}
-		long now = System.currentTimeMillis();
-		synchronized(this) {
-			timeLastReceivedPacket = now;
-			if(dataPacket)
-				timeLastReceivedDataPacket = now;
-		}
 	}
 	
 	@Override
```

**Comment by ArneBab** [comment]
Is receivePacket actually called during UOM transfer?

**Comment by Thynix** [comment]
I didn't check. That would have been good to check.

**Comment by Thynix** [comment]
I've added [remote debug support](https://github.com/freenet/scripts/commit/b56225bedcc646a8ba88f04862e89f15e246d4b8).

**Comment by ArneBab** [comment]
Wow, I didn’ t expect that to be so easy. I don’t think it needs the debug port as argument for now. That would just complicate the code for (hopefully) little gain, since we’ll (hopefully) not need remote debug for UOM very often.

**Comment by ArneBab** [comment]
@toad why did you close this?

**Comment by toad** [comment]
Because it's been merged?

**Comment by ArneBab** [comment]
ah, ok. I didn’t realize this from the state here. Sorry…

**Pull request closed without merging**
