### PR TITLE
adjust bw limit: min peers 4 and min bandwidth 5KiB/s (more risky option)

### PR DESCRIPTION
**Pull request by ArneBab**
This is one of two options I see for reducing the required peer count per bandwidth.

I see it as important, because current versions of Freenet have difficulty keeping more than 70 connections, so users with high bandwidth have flapping connections, which will stop convergence of the network.

This is the more risky option: reducing the minimum bandwidth back down to 5KiB and allowing the peers to go down to 4 — one long connection and 3 short ones. With this change, very slow nodes should contribute to routing roughly as much (or as little) as they did with 10 connections before the link length fix.

On the other hand, with this change, slow nodes should easily be able to keep all their connections.

### CODE REVIEW

**Comment by bertm** [comment]
> I see it as important, because current versions of Freenet have difficulty keeping more than 70 connections, so users with high bandwidth have flapping connections, which will stop convergence of the network.

Are you confident that this observation is not just a side-effect forced disconnects due to Frostbite and the recent mandatory update?

**Comment by ArneBab** [comment]
I’m pretty confident about that, yes, because the fraction of peers with 80 connections increased. I might still be wrong, though.

This is the old distribution: `http://127.0.0.1:8888/SSK@pxtehd-TmfJwyNUAW2Clk4pwv7Nshyg21NNfXcqzFv4,LTjcTWqvsq3ju6pMGe9Cqb3scvQgECG81hRdgj5WO4s,AQACAAE/statistics-1226/plot_peer_count.png`

This is the current one:

**Comment by xor-freenet** [comment]
@ArneBab 
> This is the old distribution: http://127.0.0.1:8888/SSK@pxtehd-TmfJwyNUAW2Clk4pwv7Nshyg21NNfXcqzFv4,LTjcTWqvsq3ju6pMGe9Cqb3scvQgECG81hRdgj5WO4s,AQACAAE/statistics-1226/plot_peer_count.png

Can you please edit your comment to include an actual copy of the image? Github allows that and it will be more convenient for reviewers & cannot fall out of the network.

> This is the current one:

Did you intentionally post an empty graph or was this a mistake?

**Comment by ArneBab** [comment]
xor-freenet <notifications@github.com> writes:

> @ArneBab 
>> This is the old distribution: http://127.0.0.1:8888/SSK@pxtehd-TmfJwyNUAW2Clk4pwv7Nshyg21NNfXcqzFv4,LTjcTWqvsq3ju6pMGe9Cqb3scvQgECG81hRdgj5WO4s,AQACAAE/statistics-1226/plot_peer_count.png
>
> Can you please edit your comment to include an actual copy of the image? Github allows that and it will be more convenient for reviewers & cannot fall out of the network.
>
>> This is the current one:
>
> Did you intentionally post an empty graph or was this a mistake?

The graph is from Steve’s site and he changed the stats collection to
not include that.

I can replace both, yes.
-- 
Unpolitisch sein
heißt politisch sein
ohne es zu merken

**Comment by ArneBab** [comment]
This should actually be less risky than I thought, because existing users should all have at least 6 connections (with the old minimum of 10KiB/s upload).

**Pull request merged**
