### PR TITLE
Remove Linkageddon and Gantros’ index from the default bookmarks

### PR DESCRIPTION
**Pull request by ArneBab**

### CODE REVIEW

**Comment by xor-freenet** [comment]
The commits of this PR were not gpg-signed. Please use Git like this in the future:
> git commit --gpg-sign your_other_parameters

**Comment by ArneBab** [comment]
@xor-freenet as you know I don’t use git to commit.

**Comment by DarknessDevil** [comment]
How to join the linkagedon?

**Comment by ArneBab** [comment]
@DarknessDevil Linkageddon is a website in Freenet. Install Freenet ( https://freenetproject.org ), then search the indexes for it.

**Pull request merged**
