### PR TITLE
Checkbox: select all friends

### PR DESCRIPTION
**Pull request by ArneBab**
This adds a feature I wanted to have for months: Just select all my friends with a single click.

A nice improvement would be to have a central place for the Javascript, but I’m not sure where to put that.

I’m working on adding the select-all logic for the queue, too. But I think it should ideally be in all tables which have check boxes on each line: click the box in the header to check or uncheck all boxes.

### CODE REVIEW

**Comment by Thynix** [comment]
This looks like nice functionality! I think it's okay to not have a non-JS alternative. It still works - just less convenient.

How about a function (a place to put this doesn't occur to me yet) that writes the Javascript to check all the boxes in a given class?

**Comment by ArneBab** [comment]
This (as independent feature) is ready for merging now. I’ll leave the generic function for another time (we’d first need to define a place for generic javascript and I think that’s something to discuss in devl - which shouldn’t  block this feature).

**Comment by Thynix** [comment]
I remain reluctant to introduce something with four copy-pasted blocks of duplicate JS.

**Comment by Thynix** [comment]
What do you think about adding a `checkall.js` to `src/freenet/clients/http/staticfiles/js`?

**Comment by Thynix** [comment]
Is there a reason to conditionally add the `<script src`?

**Comment by ArneBab** [comment]
I copied what the code in ConnectionsToadlet did: only adding Javascript when the node is set to support it.

**Comment by Thynix** [comment]
Thanks!

**Pull request merged**
