### PR TITLE
Remove more of the  db4o madness

### PR DESCRIPTION
**Pull request by nextgens**
Not tested. It compiles. 

Feedback/review is welcome

### CODE REVIEW

**Comment by nextgens** [comment]
Once this is merged we can get rid of db4o in freenet-ext

**Comment by xor-freenet** [comment]
Why does this say "Remove **more**"? I cannot find any other PR related to removing usage of db4o, isn't this the first one?

**Comment by nextgens** [comment]
You haven't looked hard enough; there's a whole branch called purge-db4o

**Comment by xor-freenet** [comment]
Ah of course, sorry. purge-db4o feels like it has become part of fred's nature already, didn't even literally remember it as a removal anymore.

**Comment by xor-freenet** [comment]
i've tested this against WoT [branch next](https://github.com/freenet/plugin-WebOfTrust/tree/3aff914346079760fa2e5921c30633e6f44c49a0):
Fetches of remote puzzles via HighLevelSimpleClient SSK fetch do **NOT** work. Seem to cause suspicious errors:
```
Jun 15, 2016 13:49:23:612 (plugins.WebOfTrust.introduction.IntroductionClient, <noname>(276), ERROR): Downloading puzzle failed: SSK@nmTkFmn0Akz1-G9iIN2w6lsQEAfWkpQw3ckOxtwMh2Q,Du9GQxGDj0Nax4zN9-ANTPetx-GxOoWaRf6Gq6Nbh1o,AQACAAE/WebOfTrust%7cIntroduction%7c2016-06-15%7c94
FetchException:The hashes in the metadata do not match the actual data. The data may have been corrupted during download, or it may have been broken when it was inserted for example if the node inserting was broken or the data changed on disk mid-insert.:null:-1:null:false:null:null
	at freenet.client.async.ClientGetWorkerThread.run(ClientGetWorkerThread.java:146)
```
The code which creates those fetches is here: https://github.com/freenet/plugin-WebOfTrust/blob/3aff914346079760fa2e5921c30633e6f44c49a0/src/plugins/WebOfTrust/introduction/IntroductionClient.java#L555

Things which do work:
- The WoT unit tests succeed
- WoT does load
- Fetching remote identities via USKManager subscriptions
- Inserting own identities via HighLevelSimpleClient SSK inserts
- Inserting own introduction puzzles via HighLevelSimpleClient SSK inserts

Things I did not test:
- Inserting puzzle solutions to KSK, as fetching puzzles doesn't even work.

**Comment by xor-freenet** [comment]
The new commit fixes the error I had explained before it, thanks!

(I won't test inserting/fetching the puzzle solution KSKs for now, that's more effort and I'd like to wait with it until the PR has settled down w.r.t. review results & fixes. Feel free to remind me when that's the case, or when you really need me to test that immediately.)

**Comment by bertm** [comment]
Doh, why was the "old" FCP code not made deprecated timely? ☹

Looks good in general, but there's a lot apparently unrelated whitespace changes that may have caused me to miss things. I'll re-read ignoring whitespace soon-ish. Not tested yet.

**Comment by bertm** [comment]
This would break Winterface, it still uses the `freenet.node.fcp` package that has never properly been marked deprecated.
I'm not sure whether that should block this pull request from being merged.

Apart from the above, the changes look good to me.

**Comment by nextgens** [comment]
It probably shouldn't. I'll merge it

**Pull request merged**
